# Generated by Django 5.2 on 2025-04-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='short_description',
            new_name='shortDescription',
        ),
        migrations.RenameField(
            model_name='retailerreceipt',
            old_name='purchase_date',
            new_name='purchaseDate',
        ),
        migrations.RenameField(
            model_name='retailerreceipt',
            old_name='purchase_time',
            new_name='purchaseTime',
        ),
    ]
